services:
  postgres:
    image: postgres:16-alpine
    container_name: str-postgres
    environment:
      POSTGRES_DB: str_platform
      POSTGRES_USER: str_user
      POSTGRES_PASSWORD: str_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U str_user -d str_platform"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - str-network

  redis:
    image: redis:7-alpine
    container_name: str-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - str-network

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: str-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: str_user
      RABBITMQ_DEFAULT_PASS: str_password
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI (http://localhost:15672)
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - str-network

  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: str-prometheus
    volumes:
      - ./infrastructure/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./infrastructure/monitoring/prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
    ports:
      - "9090:9090"
    networks:
      - str-network

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: str-alertmanager
    volumes:
      - ./infrastructure/monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - str-network

  grafana:
    image: grafana/grafana:10.4.2
    container_name: str-grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./infrastructure/monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./infrastructure/monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./infrastructure/monitoring/grafana/dashboards:/etc/grafana/dashboards:ro
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - str-network

volumes:
  postgres_data:

  grafana_data:

networks:
  str-network:
    driver: bridge
